version: '3'
services:
  outliers:
    build: .
    container_name: outliers_max_dev
    command: "python3 outliers.py interactive --config /mappedvolumes/config/outliers_max.conf --use-cases /use_cases/*.conf"
    volumes:
      - ./defaults/outliers_max.conf:/mappedvolumes/config/outliers_max.conf
      - ./use_cases/examples:/use_cases
    network_mode: sensor_network